shellEmulator: true

trustPolicy: trust
trustPolicyIgnoreAfter: 4320

packages:
  - packages/*

patchedDependencies:
  mutationobserver-shim: patches/mutationobserver-shim.patch
  vite-uxp-plugin: patches/vite-uxp-plugin.patch
