shellEmulator: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4320 # 3 days
trustPolicyExclude:
  - chokidar@4.0.3
  - sass@1.97.3

packages:
  - packages/*

patchedDependencies:
  mutationobserver-shim: patches/mutationobserver-shim.patch
  vite-uxp-plugin: patches/vite-uxp-plugin.patch
